# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c82f0de1e14ec54443e9d95c69b689458e12abc136a64f76ceda6f5599c9e53ef767dc036614d5cd7b84b741dcf4b07cc5f192e2fcdf44a55e3ba0eb992c5d78

test:
  secret_key_base: 14949ea8a02570a9185b6fb804a881be0e08bdbef4e54fdd851866164b41c5d4a743e729c275cd74f33486c514837f21a32cd909c3fb63733f6ce2c41b5f3054

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
